packages:
  - workflow
  - model
  - ui
  - .
  - test

catalog:
  '@platforma-sdk/tengo-builder': ^1.14.11
  '@platforma-sdk/block-tools': ^2.1.5
  '@milaboratory/block-builder': ^1.2.3

  '@platforma-sdk/model': ^1.2.27
  '@platforma-sdk/test': ^1.5.23
  "@milaboratory/graph-maker": ^1.0.4

  '@platforma-sdk/workflow-tengo': ^1.2.8
  '@milaboratories/software-pframes-conv': ^1.5.6

  '@milaboratory/mixcr': 4.7.0-70-develop

  '@milaboratories/uikit': ^1.2.5
  '@platforma-sdk/ui-vue': ^1.3.8
  '@milaboratories/helpers': ^1.6.2

  'vue': ^3.4.38
  'vue-tsc': ^2.1.6

  'zod': ^3.23.8
  'utility-types': ^3.11.0

  'typescript': ^5.5.4
  'tsup': ~8.1.2

  'vite': ^5.4.3
  'vitest': ^2.0.5
  '@vitejs/plugin-vue': ^5.1.3

  '@vueuse/core': ^11.0.3

  '@ag-grid-community/core': ^32.1.0
  '@ag-grid-community/client-side-row-model': ^32.1.0
  '@ag-grid-community/vue3': ^32.1.0
  '@ag-grid-community/styles': ^32.1.0

  '@changesets/cli': ^2.27.8
