packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/tengo-builder': ^1.17.5
  '@platforma-sdk/block-tools': ^2.5.3

  '@platforma-sdk/model': ^1.21.20
  '@platforma-sdk/ui-vue': ^1.21.21

  '@platforma-sdk/test': ^1.21.20
  '@milaboratories/graph-maker': ^1.1.21

  '@platforma-sdk/workflow-tengo': ^2.9.6

  '@milaboratories/software-pframes-conv': ^2.1.5
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.6
  '@platforma-open/milaboratories.software-mixcr': 4.7.0-139-develop
  '@platforma-open/milaboratories.software-mitool': 2.3.1-5-main
  '@platforma-open/milaboratories.software-paggregate': ^1.0.1

  '@milaboratories/helpers': ^1.6.11

  'vue': ^3.5.13
  'vue-tsc': ^2.2.0
  '@vueuse/core': ^12.3.0

  'zod': ^3.24.1
  'utility-types': ^3.11.0

  'typescript': ~5.6.3
  'tsup': ~8.3.5
  'turbo': ^2.3.3

  'vite': ^6.0.6
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1

  'ag-grid-enterprise': &ag-grid ^33.0.3
  'ag-grid-vue3': *ag-grid

  '@changesets/cli': ^2.27.11
