packages:
  - workflow
  - model
  - ui
  - .
  - test

catalog:
  '@platforma-sdk/tengo-builder': ^1.16.1
  '@platforma-sdk/block-tools': ^2.3.24

  "@platforma-sdk/model": ^1.8.19
  "@platforma-sdk/ui-vue": ^1.8.20

  '@platforma-sdk/test': ^1.7.53
  "@milaboratories/graph-maker": ^1.0.22

  '@platforma-sdk/workflow-tengo': ^2.1.0

  '@milaboratories/software-pframes-conv': ^2.0.1
  '@platforma-open/milaboratories.software-small-binaries': ^1.14.6
  '@platforma-open/milaboratories.software-mixcr': 4.7.0-133-develop

  '@milaboratories/helpers': ^1.6.6

  'vue': ^3.5.12
  'vue-tsc': ^2.1.10
  '@vueuse/core': ^11.2.0

  'zod': ^3.23.8
  'utility-types': ^3.11.0

  'typescript': ~5.5.4
  'tsup': ~8.1.2

  'vite': ^5.4.10
  'vitest': ^2.1.4
  '@vitejs/plugin-vue': ^5.1.5

  '@ag-grid-community/core': &ag-grid ^32.3.2
  '@ag-grid-community/client-side-row-model': *ag-grid
  '@ag-grid-community/vue3': *ag-grid
  '@ag-grid-community/styles': *ag-grid

  '@changesets/cli': ^2.27.9
