packages:
  - workflow
  - model
  - ui
  - .
  - test

catalog:
  '@platforma-sdk/tengo-builder': ^1.17.3
  '@platforma-sdk/block-tools': ^2.4.9

  "@platforma-sdk/model": ^1.17.0
  "@platforma-sdk/ui-vue": ^1.17.0

  '@platforma-sdk/test': ^1.17.0
  "@milaboratories/graph-maker": ^1.1.7

  '@platforma-sdk/workflow-tengo': ^2.6.0

  '@milaboratories/software-pframes-conv': ^2.1.2
  '@platforma-open/milaboratories.software-small-binaries': ^1.14.6
  '@platforma-open/milaboratories.software-mixcr': 4.7.0-133-develop

  '@milaboratories/helpers': ^1.6.8

  'vue': ^3.5.13
  'vue-tsc': ^2.1.10
  '@vueuse/core': ^12.0.0

  'zod': ^3.23.8
  'utility-types': ^3.11.0

  'typescript': ~5.6.3
  'tsup': ~8.3.5

  'vite': ^6.0.3
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1

  '@ag-grid-community/core': &ag-grid ^32.3.3
  '@ag-grid-community/client-side-row-model': *ag-grid
  '@ag-grid-community/vue3': *ag-grid
  '@ag-grid-community/styles': *ag-grid

  '@changesets/cli': ^2.27.10
