packages:
  - workflow
  - model
  - ui
  - .
  - test

catalog:
  '@platforma-sdk/tengo-builder': ^1.17.3
  '@platforma-sdk/block-tools': ^2.3.25

  "@platforma-sdk/model": ^1.10.12
  "@platforma-sdk/ui-vue": ^1.11.1

  '@platforma-sdk/test': ^1.10.12
  "@milaboratories/graph-maker": ^1.0.26

  '@platforma-sdk/workflow-tengo': ^2.2.1

  '@milaboratories/software-pframes-conv': ^2.0.4
  '@platforma-open/milaboratories.software-small-binaries': ^1.14.6
  '@platforma-open/milaboratories.software-mixcr': 4.7.0-133-develop

  '@milaboratories/helpers': ^1.6.6

  'vue': ^3.5.13
  'vue-tsc': ^2.1.10
  '@vueuse/core': ^11.3.0

  'zod': ^3.23.8
  'utility-types': ^3.11.0

  'typescript': ~5.5.4
  'tsup': ~8.1.2

  'vite': ^5.4.11
  'vitest': ^2.1.5
  '@vitejs/plugin-vue': ^5.2.0

  '@ag-grid-community/core': &ag-grid ^32.3.3
  '@ag-grid-community/client-side-row-model': *ag-grid
  '@ag-grid-community/vue3': *ag-grid
  '@ag-grid-community/styles': *ag-grid

  '@changesets/cli': ^2.27.10
