packages:
  - workflow
  - model
  - ui
  - .
  - test

catalog:
  '@platforma-sdk/tengo-builder': ^1.15.0
  '@platforma-sdk/block-tools': ^2.3.18

  "@platforma-sdk/model": ^1.7.16
  "@platforma-sdk/ui-vue": ^1.7.17

  '@platforma-sdk/test': ^1.7.16
  "@milaboratories/graph-maker": ^1.0.15

  '@platforma-sdk/workflow-tengo': ^1.6.3

  '@milaboratories/software-pframes-conv': ^1.6.3
  '@platforma-open/milaboratories.software-small-binaries': ^1.14.4
  '@platforma-open/milaboratories.software-mixcr': 4.7.0-113-develop

  '@milaboratories/helpers': ^1.6.5

  'vue': ^3.5.12
  'vue-tsc': ^2.1.8
  '@vueuse/core': ^11.1.0

  'zod': ^3.23.8
  'utility-types': ^3.11.0

  'typescript': ~5.5.4
  'tsup': ~8.1.2

  'vite': ^5.4.10
  'vitest': ^2.1.3
  '@vitejs/plugin-vue': ^5.1.4

  '@ag-grid-community/core': &ag-grid ^32.3.0
  '@ag-grid-community/client-side-row-model': *ag-grid
  '@ag-grid-community/vue3': *ag-grid
  '@ag-grid-community/styles': *ag-grid

  '@changesets/cli': ^2.27.9
