packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/tengo-builder': ^2.1.7
  '@platforma-sdk/block-tools': ^2.5.83
  '@platforma-sdk/eslint-config': ^1.0.3

  '@platforma-sdk/model': 1.31.6
  '@platforma-sdk/ui-vue': 1.31.11

  '@platforma-sdk/test': 1.31.13
  '@milaboratories/graph-maker': 1.1.98

  '@platforma-sdk/workflow-tengo': ^5.0.3

  '@platforma-open/milaboratories.software-small-binaries': ^1.15.19
  '@platforma-open/milaboratories.software-mixcr': 4.7.0-223-develop
  '@platforma-open/milaboratories.software-mitool': 2.3.1-5-main
  '@platforma-open/milaboratories.software-ptransform': ^1.4.3

  '@milaboratories/helpers': ^1.6.11

  'vue': ^3.5.13
  'vue-tsc': ^2.2.10
  '@vueuse/core': ^13.2.0

  'zod': ~3.23.8
  'utility-types': ^3.11.0
  
  'canonicalize': ^2.1.0

  'typescript': ~5.5.4
  'tsup': ~8.3.5
  'turbo': ^2.5.3

  'vite': ^6.3.5
  'vitest': ~2.1.8
  '@vitejs/plugin-vue': ^5.2.4

  'ag-grid-enterprise': &ag-grid ^33.0.4
  'ag-grid-vue3': *ag-grid

  '@changesets/cli': ^2.29.4
